config/routes.rb
Rails.application.routes.draw do
  

  get 'sessions/new'

  root 'pages#Home'
  get  'users/show'
  get  '/signup',  to: 'users#new'
  post '/signup',  to: 'users#create'
  get	'/list', to:  'users#listuser'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  #patch  '/signup', to: 'users#update'
  get   '/edit', to: 'users#edit'
  patch '/edit', to: 'users#update'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  attr_accessor :remember_token
  before_save { self.email = email.downcase }
  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  #validates :password, presence: true, length: { minimum: 6 }
  validates :password, presence: true, length: { minimum: 6 }, allow_nil: true
  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  # Returns a random token.
  def User.new_token
    SecureRandom.urlsafe_base64
  end

  # Remembers a user in the database for use in persistent sessions.
  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end

  # Returns true if the given token matches the digest.
  def authenticated?(remember_token)
  	return false if remember_digest.nil?
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end

  # Forgets a user.
  def forget
    update_attribute(:remember_digest, nil)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def Home
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      log_in user
      params[:session][:remember_me] == '1' ? remember(user) : forget(user)
      redirect_back_or user
    else
      flash.now[:danger] = 'Invalid email/password combination'
      render 'new'
    end
  end

  def destroy
  	log_out if logged_in?
    redirect_to root_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :logged_in_user, only: [:edit, :update]
  before_action :correct_user,   only: [:edit, :update, :show]
  before_action :admin_user,     only: :destroy
  def new
  	@user=User.new
  end

  def show
    @user=User.find(params[:id])
    if @user.nil? 
      render root_url
    else
      render 'show'
    end
  end
  
 def listuser
  	@user=User.paginate(page: params[:page], per_page: 10)
  end
  
  def edit
    @user = User.find(params[:id])
  end

  def create
     @user = User.new(user_params)
    if @user.save
      log_in @user
      flash[:success] = "Welcome "+@user.name+" the Ebook DUT!"
      redirect_to @user
    else
      render 'new'
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      flash[:success] = "Profile updated"
      redirect_to @user
      # Handle a successful update.
    else
      render 'edit'
    end
  end
  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "User deleted"
    redirect_to list_path
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password,
                                   :password_confirmation)
  end
  def log_out
    session.delete(:user_id)
    @current_user = nil
  end

  # Confirms a logged-in user.
  def logged_in_user
      unless logged_in?
        store_location
        flash[:danger] = "Please log in."
        redirect_to login_url
      end
  end
  # Confirms the correct user.
  def correct_user
      @user = User.find(params[:id])
      redirect_to(root_url) unless current_user?(@user)
  end
  # Confirms an admin user.
  def admin_user
      redirect_to(root_url) unless current_user.admin?
  end
  


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
	# Logs in the given user.
  def log_in(user)
    session[:user_id] = user.id
  end

  # Remembers a user in a persistent session.
  def remember(user)
    user.remember
    cookies.permanent.signed[:user_id] = user.id
    cookies.permanent[:remember_token] = user.remember_token
  end

  # Returns the current logged-in user (if any).
  def current_user
    if (user_id = session[:user_id])
      @current_user ||= User.find_by(id: user_id)
    elsif (user_id = cookies.signed[:user_id])
      user = User.find_by(id: user_id)
      if user && user.authenticated?(cookies[:remember_token])
        log_in user
        @current_user = user
      end
    end
  end

  # Returns true if the user is logged in, false otherwise.
  def logged_in?
    !current_user.nil?
  end

  # Forgets a persistent session.
  def forget(user)
    user.forget
    cookies.delete(:user_id)
    cookies.delete(:remember_token)
  end

  # Logs out the current user.
  def log_out
  	forget(current_user)
    session.delete(:user_id)
    @current_user = nil
  end
  # Returns true if the given user is the current user.
  def current_user?(user)
    user == current_user
  end
  # Redirects to stored location (or to the default).
  def redirect_back_or(default)
    redirect_to(session[:forwarding_url] || default)
    session.delete(:forwarding_url)
  end

  # Stores the URL trying to be accessed.
  def store_location
    session[:forwarding_url] = request.original_url if request.get?
  end
end

app/helpers/users_helper.rb
module UsersHelper

  # Returns the Gravatar for the given user.
  #def gravatar_for(user, options = { size: 80 })
   # gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    #size = options[:size]
    #gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    #image_tag(gravatar_url, alt: user.name, class: "gravatar")
  #end
  def gravatar_for(user, size: 80)
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
  
end

app/views/layouts/_footer.html.erb
<footer class="footer" >
<div class="navbar navbar-bottom">
  <nav class="navbar navbar-light bg-faded" style="float: right;">
    <ul class="nav navbar-nav">
      <li class="nav-item"><%= link_to "About",   '#' %></li>
      <li class="nav-item"><%= link_to "Contact", '#' %></li>
      <li><a href="http://news.railstutorial.org/">News</a></li>
    </ul>
  </nav>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header >
  <nav class="navbar navbar-light navbar-fixed-top bg-faded" style="text-align: right;">
  <a class="navbar-brand" href="#">Navbar</a>
  <ul class="nav navbar-nav">
    <li class="nav-item active">
      <%= link_to "Home", root_path, class: "nav-link" %>
      <!--a class="nav-link" href="#">Home <span class="sr-only">root_path</span></a-->
    </li>
    <li class="nav-item">
      <a class="nav-link" href="#">Link</a>
    </li>
    <li class="nav-item" >
      <a class="nav-link" href="#">Link</a>
    </li>
    <% if logged_in? %>
          <li class="nav-item" style="float: right;"><%= link_to "Users", list_path, class: "nav-link" %></li>
          <li class="nav-item dropdown" style="float: right;">
            <a class="nav-link dropdown-toggle" href="http://example.com" id="supportedContentDropdown" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Account</a>
            <div class="dropdown-menu" aria-labelledby="supportedContentDropdown">
              <a class="dropdown-item" href="#">Profile</a>
              <%= link_to "Settings", edit_user_path(current_user),class: "dropdown-item" %>
              <h class="divider"></h>
              <%= link_to "Log out", logout_path, method: "delete", class: "dropdown-item" %>
            </div>
          </li>
      <% else %>
        <li class="nav-item active" style="float: right;">
          <span class="glyphicon glyphicon-log-in"> <%= link_to "Login",login_path, class: "nav-link" %></span>
        </li>
      <% end %>
    <li class="nav-item active" style="float: right;">
      <span class="glyphicon glyphicon-user"> <%= link_to "Sing up", signup_path , class: "nav-link" %></span>
    </li>
    <li class="nav-item dropdown">
      <a class="nav-link dropdown-toggle" href="http://example.com" id="supportedContentDropdown" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Dropdown</a>
      <div class="dropdown-menu" aria-labelledby="supportedContentDropdown">
        <a class="dropdown-item" href="#">Action</a>
        <a class="dropdown-item" href="#">Another action</a>
        <a class="dropdown-item" href="#">Something else here</a>
      </div>
    </li>
  </ul>
  <form class="form-inline float-xs-right">
    <input class="form-control" type="text" placeholder="Search">
    <button class="btn btn-outline-success" type="submit">Search</button>
  </form>
  </nav>
  
</header>

app/views/layouts/_right.html.erb
<br>
<h3 style="text-align: center;">NEW BOOK</h3>
<br>
<ol class="list-group" style="list-style-type: decimal;">
  <li class="list-group-item"><%= link_to "new book","#"%></li>
  <li class="list-group-item"><%= link_to "new book","#"%></li>
  <li class="list-group-item"><%= link_to "new book","#"%></li>
  <li class="list-group-item"><%= link_to "new book","#"%></li>
  <li class="list-group-item"><%= link_to "new book","#"%></li>
  <li class="list-group-item"><%= link_to "new book","#"%></li>
  <li class="list-group-item"><%= link_to "new book","#"%></li>
  <li class="list-group-item"><%= link_to "new book","#"%></li>
  <li class="list-group-item"><%= link_to "new book","#"%></li>
  <li class="list-group-item"><%= link_to "new book","#"%></li>
  <li class="list-group-item"><%= link_to "new book","#"%></li>
</ol>
<br>
<br>
<br>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title) %>Library</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    
    <div class="jumbotron text-center container" style="text-align: center;">
        <img  src="/assets/top.jpg" class="center-block" style="max-width: 100%;max-height: 100%">
    </div>
  
<div class="container">
  <div class="panel panel-body" >
    <div class="row">
      <div class="col-sm-3 col-md-3 well" style="background-color:  lightgray;" class="text-justify">
        <%= render 'layouts/right' %>
        
      </div>
      <div class="col-sm-7 col-md-9 well" class="text-justify">
        <% flash.each do |message_type, message| %>
          <div class="alert alert-<%= message_type %>"><%= message %></div>
        <% end %>
        <%= yield %>
      </div>
  
      
    </div>
    <div class="panel panel-footer">
      <%= render 'layouts/footer' %>
    </div>
</div>
    
  </body>
</html>

app/views/pages/Home.html.erb
<div class="container" >
  <h4>khoa cong nghe thong tin</h4>	
  <div class="row">
    <div class="col-sm-4" style="border-radius: 5px;border: 0.5px solid black;">
      <div class="panel panel-primary" >
        <div class="panel-heading">BLACK FRIDAY DEAL</div>
        <div class="panel-body"><img src="/assets/defaut.png" class="img-circle" style="width:100%" alt="Image"></div>
        <div class="panel-footer" style="text-align: center"><%= link_to "book name","#" %></div>
      </div>
    </div>
    <div class="col-sm-4" style="border-radius: 5px;border: 0.5px solid black;">
      <div class="panel panel-primary">
        <div class="panel-heading">BLACK FRIDAY DEAL</div>
        <div class="panel-body"><img src="/assets/defaut.png" class="img-responsive" style="width:100%" alt="Image"></div>
        <div class="panel-footer" style="text-align: center"><%= link_to "book name","#" %></div>
      </div>
    </div>
    <div class="col-sm-4" style="border-radius: 5px;border: 0.5px solid black;">
      <div class="panel panel-primary">
        <div class="panel-heading">BLACK FRIDAY DEAL</div>
        <div class="panel-body"><img src="/assets/defaut.png" class="img-responsive" style="width:100%" alt="Image"></div>
        <div class="panel-footer" style="text-align: center"><%= link_to "book name","#" %></div>
      </div>
    </div>
  </div>
</div><br><br>
<div class="container">
  <h4>khoa cong nghe thong tin</h4>	
  <div class="row">
    <div class="col-sm-4" style="border-radius: 5px;border:  0.5px solid black;">
      <div class="panel panel-primary">
        <div class="panel-heading">BLACK FRIDAY DEAL</div>
        <div class="panel-body"><img src="/assets/defaut.png" class="img-responsive" style="width:100%" alt="Image"></div>
        <div class="panel-footer" style="text-align: center"><%= link_to "book name","#" %></div>
      </div>
    </div>
    <div class="col-sm-4" style="border-radius: 5px;border:  0.5px solid black;">
      <div class="panel panel-primary">
        <div class="panel-heading">BLACK FRIDAY DEAL</div>
        <div class="panel-body"><img src="/assets/defaut.png" class="img-responsive" style="width:100%" alt="Image"></div>
        <div class="panel-footer" style="text-align: center"><%= link_to "book name","#" %></div>
      </div>
    </div>
    <div class="col-sm-4" style="border-radius: 5px;border: 0.5px solid black;">
      <div class="panel panel-primary">
        <div class="panel-heading">BLACK FRIDAY DEAL</div>
        <div class="panel-body"><img src="/assets/defaut.png" class="img-responsive" style="width:100%" alt="Image"></div>
        <div class="panel-footer" style="text-align: center"><%= link_to "book name","#" %></div>
      </div>
    </div>
  </div>
</div><br><br>
<div class="container">
  <h4>khoa cong nghe thong tin</h4>	
  <div class="row">
    <div class="col-sm-4" style="border-radius: 5px;border: 0.5px solid black;">
      <div class="panel panel-primary">
        <div class="panel-heading">BLACK FRIDAY DEAL</div>
        <div class="panel-body"><img src="/assets/defaut.png" class="img-responsive" style="width:100%" alt="Image"></div>
        <div class="panel-footer" style="text-align: center"><%= link_to "book name","#" %></div>
      </div>
    </div>
    <div class="col-sm-4" style="border-radius: 5px;border: 0.5px solid black;">
      <div class="panel panel-primary">
        <div class="panel-heading">BLACK FRIDAY DEAL</div>
        <div class="panel-body"><img src="/assets/defaut.png" class="img-responsive" style="width:100%" alt="Image"></div>
        <div class="panel-footer" style="text-align: center"><%= link_to "book name","#" %></div>
      </div>
    </div>
    <div class="col-sm-4" style="border-radius: 5px;border: 0.5px solid black;">
      <div class="panel panel-primary">
        <div class="panel-heading">BLACK FRIDAY DEAL</div>
        <div class="panel-body"><img src="/assets/defaut.png" class="img-responsive" style="width:100%" alt="Image"></div>
        <div class="panel-footer" style="text-align: center"><%= link_to "book name","#" %></div>
      </div>
    </div>
  </div>
</div><br><br>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li style="list-style-type: none"><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages' %>
      </br>
      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>
      </br>
      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>
      </br>
      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>
      </br>
      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>
      </br>
      <%= f.submit yield(:button_text), class: "btn btn-primary btn-block"  %>
    <% end %>

app/views/users/_user.html.erb
<li>
  <%= gravatar_for user, size: 50 %>
  <%= link_to user.name, user %>
</li>

app/views/users/edit.html.erb
<% provide(:title, 'Edit user') %>
<% provide(:button_text, 'Save changes') %>
<h1 style="text-align: center;">Update your profile</h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3" style="margin-left: 30%">
    <%= render 'form' %>
    </br>
    <div class="gravatar_edit">
      <%= gravatar_for @user %>
      <a href="http://gravatar.com/emails" target="_blank">Change</a>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<% provide(:title, 'All users') %>
<h1>All users</h1>

<ul class="users">
  <% @users.each do |user| %>
    <li>
      <%= gravatar_for user, size: 50 %>
      <%= link_to user.name, user %>
    </li>
  <% end %>
</ul>

app/views/users/listuser.html.erb
<% provide(:title, 'ALL USER') %>
<h1 style="text-align: center;">ALL USER</h1>

<ul class="users list-group" style="margin-left: 0%;list-style-type: none;">
<% @user.each do |user| %>
    <li class="list-group-item" >
  	
    	<div class="col-md-12 ">
    		<div class="col-md-4" style=" display: inline;">
    			<!--a href=user-->
    				<%= gravatar_for(user,size: 30) %> 
    				<span class="glyphicon glyphicon-user"></span>
    				<%= link_to  user.name, user  %>
    			<!--/a-->
    		</div>
    		<div class="col-md-8">
    			<% if current_user.admin? && !current_user?(user) %>
                <%= link_to "delete", user, method: :delete,data: { confirm: "You sure?" } %>
               <% end %>                   
    		</div>
    	</div>
        
        
        <br>
    </li>
<% end %>
</ul>

<ul class="pager" style="list-style-type: none;">
  <li ><%= will_paginate @user%></li>
</ul>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<% provide(:button_text, 'Create my account') %>
<h1 style="text-align: center;">Sign up</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3"  style="margin-left:  25%; ">
    <%= render 'form' %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <h1>
        <%= gravatar_for(@user,size: 80) %>
        <%= @user.name %>
      </h1>
    </section>
  </aside>
</div>